apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: nodejs-hello-world
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: nodejs-hello-world
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 90

---
apiVersion: v1
kind: Service
metadata:
  name: nodejs-hello-world
  labels:
    app: nodejs-hello-world
spec:
  ports:
  - port: 8080
  # not sure if i need this...
  selector:
    app: nodejs-hello-world

---

apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: nodejs-hello-world
spec:
  selector:
    matchLabels:
      app: nodejs-hello-world
  # replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: nodejs-hello-world
    spec:
      containers:
      - name: nodejs-hello-world
        image: mrslwiseman/nodejs-hello-world:0.0.1
        ports:
        - containerPort: 8080
        resources:
          # limits:
          #   cpu: 500m
          requests:
            cpu: 1
